spring:
  application:
    name: ccsr-example

ohara-mcs:
  rpc-type: grpc     # 客户端与服务端通信协议
  cluster-address:
    - 127.0.0.1:8010 # 服务端集群地址
    - 127.0.0.1:8011
    - 127.0.0.1:8012
#    - 127.0.0.1:8300
  namespace: default # 命名空间

# HTTP 端口
server:
  port: 9527


