spring:
  application:
    name: xxx

ohara-mcs:
  rpc-type: grpc     # 客户端与服务端通信协议
  cluster-address:
    - 127.0.0.1:8000 # 服务端集群地址
    - 127.0.0.1:8100
    - 127.0.0.1:8200
    - 127.0.0.1:8300
  namespace: default # 命名空间

# HTTP 端口
server:
  port: 9527


